runtime: nodejs16

instance_class: F2

env_variables:
  JWT_SECRET_KEY: "1234567890qwertyuiopasdfghjklzxcvbnm"
  JWT_COOKIE_EXPIRE: 1
  NODE_ENV: "gcpdb"

  # PORT connection
  PORT: 3001

  # setting database
  DB_USERNAME: "lrandjai"
  DB_PASSWORD: "JW8dOFMZl87VZJZujjzM8GBMMZ9N5uS_"
  DB_NAME: "lrandjai"
  DB_PORT: 5432
  DB_HOST: "rosie.db.elephantsql.com"
  DB_DIALECT: "postgres"

  # redis
  DB_REDIS_URL: "redis://redis-14875.c252.ap-southeast-1-1.ec2.cloud.redislabs.com:14875"
  DB_REDIS_PASS: "OuEOVgmfWwqIBXc3fqDECYCH6zzSi6SX"

  # setting database gcp
  DB_USERNAME_GCP: "postgres"
  DB_PASSWORD_GCP: "c*Q=<3k6R(kbooRD"
  DB_NAME_GCP: kg-old-v1
  DB_PORT_GCP: 5432
  DB_HOST_GCP: 34.124.179.216

  # setting OAuth2
  GOOGLE_CLIENT_ID: "888715233325-6umod6g1btsv85r100gh2mmji8h9r4b6.apps.googleusercontent.com"
  GOOGLE_CLIENT_SECRET: "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"

  # setting nodemailer
  # SERVER_MAIL_ADDRESS :
  # SERVER_MAIL_PASS :

  # sentry.io
  SENTRY_DSN: "https://3592d0bb9b934a52a478b18e3ef7b2f1@o1421697.ingest.sentry.io/6767797"
